application: aristidesfl
version: 1
runtime: python
api_version: 1

handlers: 

  - url: /fonts
    static_dir: static/fonts
    
  - url: /girl_square.gif
    static_files: static/girl_square.gif
    upload: static/girl_square.gif
   
  - url: /reset.css
    static_files: static/reset.css
    upload: static/reset.css
  
  - url: /rot13.js
    static_files: static/rot13.js
    upload: static/rot13.js

  - url: /draw.js
    static_files: static/draw.js
    upload: static/draw.js    
    
  - url: /favicon.ico
    static_files: static/favicon2.ico
    upload: static/favicon2.ico
  
  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt

  - url: /publickey.asc
    static_files: static/publickey.asc
    upload: static/publickey.asc

  - url: /prey.html
    static_files: static/prey.html
    upload: static/prey.html
      
  - url: /
    static_files: static/index.html
    upload: static/index.html         

  - url: /.*
    script: main.py